name: Create Release For Tag
on: { push: { tags: [ 'v*' ] } }
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create GitHub release
        uses: infrabits/ci-create-missing-release@d269a3c6b440e23e2a3b43fd60eb1a5bec5a1e60 # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag: '${{ github.ref }}'
