name: Create Release For Tag
on: { push: { tags: [ 'v*' ] } }
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create GitHub release
        uses: infrabits/ci-create-missing-release@7887466cff50f3885bf0c270cab70d22246f748e # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tag: '${{ github.ref }}'
